version: '3'
services:
  db:
    build: db
    expose:
      - '5432'
    env_file:
      - db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  service:
    build: app
    depends_on:
      - db
    expose:
      - '8000'
    env_file:
      - app/.env
    volumes:
      - static:/opt/app/static/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - static:/var/www/static/
    depends_on:
      - db
      - service
    ports:
      - '80:80'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    expose:
      - '9200'

  postgres_to_es:
    build: postgres_to_es
    depends_on:
      - db
      - elasticsearch
    env_file:
      - postgres_to_es/.env


volumes:
  static:
  postgres_data: